name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk build-essential git python3 python3-pip
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          pip install Cython
          buildozer -v android debug
        env:
          ANDROIDSDK: ${{ github.workspace }}/.android/sdk
          ANDROIDNDK: ${{ github.workspace }}/.android/ndk

